---
date: 2023-05-26 10:00
title: "Minicurso 1: Rcmdr em Sala de Aula - Uma Aplicação com Dados da COVID-19"
youtube: fobDm1l3WJY
event: 3º Educa-SER
---

## Resumo

pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó pipipipópópó 
